version : '3.3'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: uncodev-db
    restart: always
    networks:
      - backend
    env_file : 
      - ./app/config/.env
    ports:
      - '5432:5432'
    volumes: 
      - db_data:/var/lib/postgresql/data
  app:
    build : app
    ports : 
        - 8080:8080
    networks : 
        - backend
    image : app
    container_name: app
    depends_on: 
        postgres: 
          condition : service_healthy


volumes : 
  db_data : 

networks:
  backend:
    driver : bridge


